### ISSUE TITLE
Missed description for items created from Word 

### ISSUE THREAD

**Issue by mmarkov** [SoftServeInc/SALMA#10]
Issue: I created content in Word Document and based on this content created item in TFS. Title is correct, items are linked, but in TFS description is empty. 

Environment: Microsoft Word 2013,  Visual Studio On Demand

Steps to reproduce:
1. Install salma - http://softserveinc.github.io/SALMA/res/salma-setup-1.7.exe
2. Connect word to sscondulting.visualstudio.com
3. Select paragraph of test
4. in SALMA ribbon Click "Create New"
5. Choose "User story" and provide title
6. Comment appear in Word document
7. Navigate to TFS and ensure that selected text is not provided as description

By the way - bidirectional update works fine for acceptance criteria

**Comment by imatrofaylo** [comment]
No sure if this is a bug. Need confirmation from Nazar.

Environment: Microsoft Word 2013, Visual Studio On Demand

Currently it is possible to add comment using following steps:
1. Install salma - http://softserveinc.github.io/SALMA/res/salma-setup-1.7.exe
2. Connect word to http://ssconsulting.visualstudio.com
3. Select PARAGRAPH TITLE in word document
4. In SALMA ribbon Click "Create New"
5. Choose "User story" and provide title (paragraph title will be preset as title of User Story by default).
6. Comment with newly created User Story appear in Word document.
7. Select PARAGRAPH CONTENT in word document
8. In SALMA ribbon Click "Add Details"
9. Selected newly created story in the list by word item add. Select details field as Description. And press Add.
10. Comment with User Story updated in Word Document
11. Navigate to TFS and ensure that new User Story is created, where:
- User Story name =  PARAGRAPH TITLE
- User Story description = PARAGRAPH CONTENT

**Comment by mmarkov** [comment]
I am not sure what are PARAGRAPH TITLE and
PARAGRAPH CONTENT.

Do you mean I should create heading in the word document? Or I can use 2
arbitrary paragraphs?

**Comment by nkravch** [comment]
Everything works perfectly. Please follow a simple instruction:
1. select any short text (candidate to WorkItem Title) in word document and click create new. This text will be copied to pop-up dialogue window. Select WI type → click ok. 
Now you have created empty WI with title that you have selected in step before. 
2. Select any other bulk of text - that would be a description of WI (in case of e.g Bug - it will be "Steps to reproduce") → click add details and select WI in Document or by ID → click OK. 
It will supplement WI with content

**Comment by mmarkov** [comment]
Could you, please, also try to add description to item created in TFS?
1. Create item in TFS
2. Open word document
3. Write some paragraph
4. Add paragraph as details to item from #1

For some strange reasons I could not achieve this as well.

With kind regards,
Max

**Comment by nkravch** [comment]
"Could you, please, also try to add description to item created in TFS? ... "
Work like a charm! 
Be sure that you have established connection and refresh WI window

**Comment by mmarkov** [comment]
It looks like I was using wrong release - fixed in pull request #11
